### PR TITLE
Update Alpine to v3.18

### PR DESCRIPTION
**Pull request by dalbani**
Alpine 3.18.0 has been released on 2023-05-09.
See https://www.alpinelinux.org/releases/.

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
@dalbani Are you able to sign the Eclipse Contributor Agreement?

**Comment by dalbani** [comment]
I did try several times to sign the ECA yesterday, but apparently it didn't worked.
I've just tried again and now it went through.

**Review by lyca — APPROVED** [review]

**Review by domenjesenovec — APPROVED** [review]

**Comment by dalbani** [comment]
Out of curiosity, what are the next steps to have this change merged?

**Review by gdams — APPROVED** [review]

**Comment by dalbani** [comment]
Excellent 👍

**Comment by dalbani** [comment]
Speaking of Alpine version, I'm wondering how this change in the Dockerfile relates to the version at https://github.com/adoptium/infrastructure/blob/d9b705d1c8568083cf27bf19586e14d3c6c773cf/ansible/docker/Dockerfile.Alpine3#L1
```
FROM alpine:3.15
```
I saw this PR which mentions an issue to Alpine > v3.15: https://github.com/adoptium/infrastructure/pull/2628.
(I've actually tried building `alpine_build_image` locally with `FROM alpine:3.18` and it didn't throw any compilation.)

Correct me if I'm wrong, but it thus looks like the Docker image is based on v3.18 from now on, even though it contains binaries from e.g. `OpenJDK11U-jdk_x64_alpine-linux_hotspot_11.0.19_7.tar.gz` which has been build in an Alpine v3.15 environment. Am I right?
I suppose it's no different that the Docker images for Ubuntu 20.04 (https://github.com/adoptium/containers/blob/main/11/jdk/ubuntu/focal/Dockerfile.releases.full) and 22.04 (https://github.com/adoptium/containers/blob/main/11/jdk/ubuntu/jammy/Dockerfile.releases.full) also relying on the same OpenJDK archive.
Probably a silly question, but is that a "safe" choice, as in reliable?

**Comment by karianna** [comment]
Our infra versions are what we build on and often lag our target due to backwards compatibility requirements.

**Comment by dalbani** [comment]
Then maybe my question was more: is there an official compatibility matrix for the Adoptium packages?
In the sense of, what version/kind of "Linux", "MacOS", "AIX", etc is actually meant on the list for https://adoptium.net/temurin/releases/?version=11 for example?

**Comment by gdams** [comment]
> Then maybe my question was more: is there an official compatibility matrix for the Adoptium packages? In the sense of, what version/kind of "Linux", "MacOS", "AIX", etc is actually meant on the list for https://adoptium.net/temurin/releases/?version=11 for example?

yup take a look at https://adoptium.net/supported-platforms/

**Pull request merged**
