### PR TITLE
Add Docker pulls badge

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Comment by tellison** [comment]
May be a bit lost on this 'functional' repository. No objection to it being here, but consider also adding it to a [more visible location](https://github.com/adoptium/.github/blob/main/profile/README.md)?

**Comment by gdams** [comment]
> May be a bit lost on this 'functional' repository. No objection to it being here, but consider also adding it to a [more visible location](https://github.com/adoptium/.github/blob/main/profile/README.md)?

Yeah I don't disagree, I'll merge this here but we should consider additional locations

**Comment by tellison** [comment]
[This link](https://img.shields.io/docker/pulls/_/eclipse-temurin?label=Docker%20Pulls) works for me, but this PR is rendering as:

Screenshot 2022-11-01 at 14 29 53

**Comment by zdtsw** [comment]
Screenshot from 2022-11-01 15-41-03
i got this, seems fine

**Comment by tellison** [comment]
Thanks Wen - works for me too now. shrug/

**Pull request merged**
