### PR TITLE
add riscv64 support

### PR DESCRIPTION
**Pull request by gdams**
This PR adds support for riscv64 Docker images 🎉

### CODE REVIEW

**Comment by sxa** [comment]
> I cannot recreate the error locally when building like this:

For what it's worth when I tried running on an Ubuntu 23.04 host (native riscv64) I had an issue with the repositories for sid:
```
$ docker run -it debian:sid-slim
root@a166693ac07f:/# apt-get -y update
Get:1 http://deb.debian.org/debian-ports sid InRelease [80.4 kB]
Get:2 http://deb.debian.org/debian-ports unreleased InRelease [54.1 kB]
Fetched 134 kB in 1s (122 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-riscv64/Packages' as repository 'http://deb.debian.org/debian-ports sid InRelease' doesn't support architecture 'riscv64'
N: Skipping acquire of configured file 'main/binary-riscv64/Packages' as repository 'http://deb.debian.org/debian-ports unreleased InRelease' doesn't support architecture 'riscv64'
```

**Comment by yosifkit** [comment]
> 0.156 exec /bin/sh: exec format error

I think this error is because GitHub actions runners aren't automatically setup with user-mode qemu like when using Docker Desktop.

As far as adding Debian Unstable based builds, we wouldn't do it in images we directly maintain since it is actually unstable (https://wiki.debian.org/DebianUnstable)
>having images based on Debian Unstable leads to a lot of not-unexpected instability both in our own builds and in the downstream builds of our users
\- https://github.com/docker-library/golang/issues/435#issuecomment-1648671784

**Comment by gdams** [comment]
> > 0.156 exec /bin/sh: exec format error
> 
> I think this error is because GitHub actions runners aren't automatically setup with user-mode qemu like when using Docker Desktop.
> 
> As far as adding Debian Unstable based builds, we wouldn't do it in images we directly maintain since it is actually unstable (https://wiki.debian.org/DebianUnstable)
> 
> > having images based on Debian Unstable leads to a lot of not-unexpected instability both in our own builds and in the downstream builds of our users
> > - [docker-library/golang#435 (comment)](https://github.com/docker-library/golang/issues/435#issuecomment-1648671784)

Right okay, I'll see if I can implement some changes to set. the user-mode qemu when running non intel builds.

As for the base image, it sounds like we're stuck until Ubuntu add support to their official images again. Do you know who I can reach out to resolve this?

**Review by tellison — APPROVED** [review]

**Review by steelhead31 — APPROVED** [review]
Looks good!

**Review by sxa — APPROVED** [review]
Approving (Noting that I haven't manually verified the ESUM values!)

**Pull request merged**
