### PR TITLE
Fix Gradle v7.5+ not working with UBI based Docker images

### LINKED ISSUE #462: [Bug]: Gradle v7.5+ not working with UBI based Docker images
### Please add the exact image (with tag) that you are using

eclipse-temurin:21.0.1_12-jdk-ubi9-minimal

### Please add the version of Docker you are running

Docker version 24.0.7, build afdd53b

### What happened?

Gradle v7.5+ builds with UBI based Eclipse Temurin Docker images fail with the following error, as `findutils` and therefore also `xargs` is not installed in the Docker image.
```sh
xargs is not available
```

The `findutils` utils are **available in the Ubuntu and Alpine Linux based Docker images**, _there the Gradle builds do not fail_.

See:
https://stackoverflow.com/a/75660631/5666188
https://github.com/gradle/gradle/issues/19682
https://github.com/gradle/gradle/commit/0495e5e680da994442f124aa8b422d248d32049d

Please include `findutils` after the following line, so the command `xargs` is present as it is in the Ubuntu and Alpine Linux based Docker images:
```sh
        # Required for Gradle v7.5+ which requires the command xargs (included in findutils)
        findutils \
```

https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/docker_templates/ubi9-minimal.Dockerfile.j2#L20

https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/21/jre/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/21/jdk/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/20/jre/ubi/ubi9-minimal/Dockerfile.releases.full#L28
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/20/jdk/ubi/ubi9-minimal/Dockerfile.releases.full#L28
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/19/jre/ubi/ubi9-minimal/Dockerfile.releases.full#L28
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/19/jdk/ubi/ubi9-minimal/Dockerfile.releases.full#L28
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/17/jre/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/17/jdk/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/11/jre/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/11/jdk/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/8/jre/ubi/ubi9-minimal/Dockerfile#L41
https://github.com/adoptium/containers/blob/376294c245eba65108cee487ce209f39c15e84c8/8/jdk/ubi/ubi9-minimal/Dockerfile#L41

### Relevant log output

```shell
./gradlew build

xargs is not available
```

### PR DESCRIPTION
**Pull request by ThoSap**
Fixes #462 Gradle v7.5+ not working with UBI based Docker images.

### CODE REVIEW

**Comment by ThoSap** [comment]
For this change I just added the package here `docker_templates/ubi9-minimal.Dockerfile.j2` and then generated the images using `generate_dockerfiles.py`

I manually added the package for these Dockerfile's, as the .j2 template does not influence these ones:
- 19/jre/ubi/ubi9-minimal/Dockerfile.releases.full
- 19/jdk/ubi/ubi9-minimal/Dockerfile.releases.full
- 20/jre/ubi/ubi9-minimal/Dockerfile.releases.full
- 20/jdk/ubi/ubi9-minimal/Dockerfile.releases.full

**Comment by gdams** [comment]
CC @keeganwitt (the official Gradle image maintainer)

**Comment by ThoSap** [comment]
My change just installs the dependency `findutils`, which is required by Gradle to be able to use the command `xargs` and is usually pre-installed by each of the Linux distros in the wild.

The Ubuntu and Alpine Linux based Eclipse Temurin images ship with `findutils`, therefore Gradle 7.5+ works.
Therefore I wanted to add this dependency, so each of the Temurin flavors have the same baseline.
https://www.gnu.org/software/findutils/
https://man7.org/linux/man-pages/man1/xargs.1.html

**Comment by gdams** [comment]
> My change just installs the dependency `findutils`, which is required by Gradle to be able to use the command `xargs` and is usually pre-installed by each of the Linux distros in the wild.
> 
> The Ubuntu and Alpine Linux based Eclipse Temurin images ship with `findutils`, therefore Gradle 7.5+ works. Therefore I wanted to add this dependency, so each of the Temurin flavors have the same baseline. https://www.gnu.org/software/findutils/ https://man7.org/linux/man-pages/man1/xargs.1.html

Yeah I totally understand what you're saying, my concern is explicitly adding a package to our images. Especially as they are meant to be minimal images. I'd like to see what @keeganwitt suggests first, I'd much prefer the Gradle project ship an official image for UBI (which would then contain any additional dependencies)

**Comment by keeganwitt** [comment]
I'm not currently providing UBI-based official Gradle images, though it's something I'd consider if I can understand the use-case a little better.

The Gradle images were meant for using a globally-installed Gradle rather than the wrapper, which it sounds like is what @ThoSap is currently using. Still, in general I'd agree that something that's a Gradle-specific dependency would likely make sense to avoid adding to this base image. If you're wanting to stick with the wrapper, maybe it'd make sense to invoke the wrapper using the Gradle image (kind redundant, but at least you'd have the dependencies you need there).

**Comment by karianna** [comment]
Going to close this based on the advice given (and our general policy to be as minimal as possible).

**Comment by keeganwitt** [comment]
@ThoSap Please open an issue on https://github.com/keeganwitt/docker-gradle/ and explain the benefit of UBI-based images.

**Pull request closed without merging**
