### PR TITLE
Patch busybox vulnerabilities

### PR DESCRIPTION
**Pull request by saefty**
https://alpinelinux.org/posts/Alpine-3.14.3-released.html

### CODE REVIEW

**Comment by saefty** [comment]
An alternative to applying this PR is to rebuild the images, alpine:3.14 is refering to the same image as alpine:3.14.3
Both processes require human interaction. I am wondering if it woudn't be better to use a fixed version here and have a PR / sth like depndabot updating the image.
image

**Comment by tianon** [comment]
If you look at https://hub.docker.com/_/eclipse-temurin?tab=tags&page=1&name=17-jdk-alpine, you can see that `eclipse-temurin:17-jdk-alpine` was pushed around the exact same timeframe as the last push on the Alpine base image -- official images are all automatically rebuilt any time their base is updated.

Another way to see this is to pull the latest image and try to apply updates:

```console
$ docker pull eclipse-temurin:17-jdk-alpine
17-jdk-alpine: Pulling from library/eclipse-temurin
Digest: sha256:32b5c3ab0a254b9fcfdd6fce9ac968c7d1f8b2785cfbd39643eaf1c08774d7aa
Status: Image is up to date for eclipse-temurin:17-jdk-alpine
docker.io/library/eclipse-temurin:17-jdk-alpine
$ docker run -it --rm eclipse-temurin:17-jdk-alpine sh
/ # apk upgrade --update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
OK: 9 MiB in 17 packages
```

(You can see there are no package updates available.)

**Comment by karianna** [comment]
@gdams - I'm a little unsure if this is where we should accept this patch. Thoughts?

**Comment by gdams** [comment]
As far as I'm aware this change is not needed. As @tianon mentioned the images are rebuilt every time the base image is rebuilt so we should always have the latest Alpine patches in our images. Closing for now

**Pull request closed without merging**
