### PR TITLE
Add Ubuntu lunar 23.04 in config/hotspot.yml

### PR DESCRIPTION
**Pull request by tinours**
Add Ubuntu lunar 23.04 in config/hotspot.yml

Signed-off-by David Bergeron <david.bergeron5@usherbrooke.ca>

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by tinours** [comment]
Depend on pull request #471

Because the script generate_dockerfiles.py
Do not work in all versions of ubuntu to generate the entrypoint.sh file.

**Review by sxa — COMMENTED** [review]
I'm very much -1 on this unless I've missed something - has it been discussed anywhere prior to this PR being created? As I understand it this PR is looking to change the versions that we are supporting as official images, and we do not generally have non-LTS versions in our set.

23.04 is out of support this month
23.10 is the current latest version that is in support, but that is not an LTS release so I'm not sure why we would make such a change to include it.

**Review by karianna — CHANGES_REQUESTED** [review]
As per @sxa comments

**Comment by gdams** [comment]
Sorry out policy is to only support LTS versions in our official docker images

**Pull request closed without merging**
